Dolci/paper notebook
firedrakeproject/checkpoint_schedules pull request #38
Opened 2023-09-07 14:30 UTC by Ig-dolci

The paper was reviewed by David.

2023-09-15 12:44 UTC, jrmaddison requested changes
See also edits to the tutorial.

2023-09-15 12:44 UTC, jrmaddison commented on docs/paper/paper.md
> +*checkpointing_schedules* has been integrated into **tlm_adjoint** [@Maddison2014],
The correct tlm_adjoint reference is: https://doi.org/10.1137/18M1209465

2023-09-15 12:50 UTC, jrmaddison commented
Also my affiliation is: School of Mathematics and Maxwell Institute for Mathematical Sciences, University of Edinburgh

2023-09-18 08:24 UTC, Ig-dolci commented
This PR contains the paper reviewed by David and James. The notebooks tutorial.ipynb was reviewed by James.

2023-09-18 08:24 UTC, merged